### PR TITLE
fix(infinite install): Stop after first install

### LINKED ISSUE #28: Stryker is currently not installed loop
Originally reported by @mjh5153

When I go to run the command Stryker run, I keep getting prompted that Stryker is currently not installed. I can see that Stryker and Stryker-api are installed via node modules and package.json.

screenshot

https://github.com/stryker-mutator/stryker/issues/414

### PR DESCRIPTION
**Pull request by nicojs**
Make sure question about installing stryker is only prompted when stryker cannot be found. Only the first time.

* Add error handling for different types of errors
* Add unit tests

Fixes #28

### CODE REVIEW

**Comment by nicojs** [comment]
@korthout @avassem85 do one of you want to take a look at this one?

**Comment by korthout** [comment]
I'm on it ;)

File: src/stryker-cli.ts [hunk 1]
```diff
@@ -1,68 +1,64 @@
...
+  log(chalk.yellow('Stryker is currently not installed.'));
+  return inquirer.prompt([{
     type: 'confirm',
     name: 'install',
-    message: 'Do you want to automatically install Stryker?',
-    default: 'true'
-  }]).then((answers) => {
-    if (answers['install']) {
-      installStryker();
+    message: 'Do you want to install Stryker locally? (npm install --save-dev stryker stryker-cli)',
```
Comment (korthout) [inline src/stryker-cli.ts]: We actually execute `npm install --save-dev stryker stryker-api` to install `stryker` locally. I think `stryker-cli` might have been a typo. Also considering the user is already using the cli at this moment.

File: src/stryker-cli.ts [hunk 2]
```diff
@@ -1,68 +1,64 @@
...
+    choices: ['Yes, of course!', 'Nope, not today.'],
+    default: 'Yes, of course!'
+  }]).then((answers: inquirer.Answers) => {
+    if (answers['install'] === 'Yes, of course!') {
+      return true;
     } else {
-      console.log(`I understand. You can install Stryker manually using ${chalk.blue('`npm install stryker`')}.`);
+      log(`Ok, I don't agree, but I understand. You can install Stryker manually using ${chalk.blue('npm install stryker stryker-api --save-dev')}.`);
```
Comment (korthout) [inline src/stryker-cli.ts]: For consistency, it might be nice to use the exact same string for manual installation of `stryker` as was used before. So, `npm install --save-dev stryker stryker-api`. I recommend you remove the duplication. If you then need to change it again at some point later in time, you won't forget to update the other locations.

File: test/unit/stryker-cli.spec.ts [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+    stubs.resolve.returns('path/to/local/stryker');
+    stubs.require.throws(new Error(`Error: Cannot find module 'FooBar'`));
+    return expect(run(stubs.log)).rejectedWith(`Error: Cannot find module 'FooBar'`);
+  });
+
+  it('should not prompt again when failing a second time (with any error)', () => {
+    stubs.resolve.throws(new Error(`Error: Cannot find module 'stryker'`));
+    stubs.prompt.resolves({ install: yes });
+    return expect(run(stubs.log)).to.eventually.rejectedWith(`Error: Cannot find module 'stryker'`);
+  });
```
Comment (korthout) [inline test/unit/stryker-cli.spec.ts]: I feel like this test does not check what the message states it does. It should check whether the user wasn't prompted again after failing a second time. What about something like:

```
it('should not prompt again when failing a second time (with any error)', async () => {
  stubs.resolve
    .onFirstCall().throws(new Error(`Error: Cannot find module 'stryker'`))
    .onSecondCall().throws(new Error(`Error: Cannot find module 'stryker'`));
  stubs.prompt.resolves({ install: yes });
  await expect(run(stubs.log)).to.eventually.rejectedWith(`Error: Cannot find module 'stryker'`);
  expect(stubs.resolve).calledTwice; // to verify that there actually was a second time
  expect(stubs.prompt).calledOnce; // the actual check
  expect(stubs.execSync).not.called; // lastly checking that we didn't still try the call
});
```

File: test/unit/stryker-cli.spec.ts [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+    await run(stubs.log);
+    expect(stubs.execSync).not.called;
+    expect(stubs.log).calledWith(`Ok, I don't agree, but I understand. You can install Stryker manually ` +
+      `using ${chalk.blue('npm install stryker stryker-api --save-dev')}.`);
+  });
+
+  it('should pass all other errors', () => {
+    stubs.resolve.returns('path/to/local/stryker');
+    stubs.require.throws(new Error(`Error: Cannot find module 'FooBar'`));
+    return expect(run(stubs.log)).rejectedWith(`Error: Cannot find module 'FooBar'`);
```
Comment (korthout) [inline test/unit/stryker-cli.spec.ts]: I would expect this test to also check that we didn't try to forward the commands to `stryker`, which may lead to addition errors in the logging for the user.

File: src/stryker-cli.ts [hunk 5]
```diff
@@ -1,68 +1,64 @@
...
-    message: 'Do you want to automatically install Stryker?',
-    default: 'true'
-  }]).then((answers) => {
-    if (answers['install']) {
-      installStryker();
+    message: 'Do you want to install Stryker locally? (npm install --save-dev stryker stryker-cli)',
+    choices: ['Yes, of course!', 'Nope, not today.'],
+    default: 'Yes, of course!'
+  }]).then((answers: inquirer.Answers) => {
+    if (answers['install'] === 'Yes, of course!') {
```
Comment (korthout) [inline src/stryker-cli.ts]: Oops I missed this one. Simply checking whether `answers['install']` holds is enough. Checking that the answer is strictly equal to `Yes, of course!` doesn't seem to work when I try it locally.

File: src/stryker-cli.ts (hunk 1 above)
Comment (korthout) [inline src/stryker-cli.ts]: We actually execute `npm install --save-dev stryker stryker-api` to install `stryker` locally. I think `stryker-cli` might have been a typo. Also considering the user is already using the cli at this moment.

Comment (korthout) [reply src/stryker-cli.ts]: I'm making some mistakes with the review. This was part of the original review.

File: src/stryker-cli.ts (hunk 5 above)
Comment (korthout) [inline src/stryker-cli.ts]: I forgot about this part. Simply checking whether `answers['install']` holds is enough for the prompt. Checking that the answer is strictly equals to `Yes, of course!` is actually not working for me locally. So I recommend to use: 
```
if (answers['install']) {
```

**Comment by nicojs** [comment]
Thanks for the detailed review! I will take a look later today

File: src/stryker-cli.ts (hunk 2 above)
Comment (nicojs) [reply src/stryker-cli.ts]: Good point!

File: test/unit/stryker-cli.spec.ts (hunk 4 above)
Comment (nicojs) [reply test/unit/stryker-cli.spec.ts]: What do you mean? `require` throws an error, so commands are already forwarded, right?

File: test/unit/stryker-cli.spec.ts (hunk 3 above)
Comment (nicojs) [reply test/unit/stryker-cli.spec.ts]: Brilliant! Except the last call (execSync is called once, the first time). I will add this to the test.

File: src/stryker-cli.ts (hunk 1 above)
Comment (nicojs) [reply src/stryker-cli.ts]: True.. typo. Fixed by removing duplicated code. Good catch!

File: src/stryker-cli.ts (hunk 5 above)
Comment (nicojs) [reply src/stryker-cli.ts]: True! This part didn't even work. I was too fast with refactoring. The `choices` are not used if type is `'confirm'`.

**Comment by nicojs** [comment]
Thanks for the review. I've fixed it with a new commit. If you agree, i suggest merging it with "Squash and merge" to get a clean history and commit message.

**Comment by nicojs** [comment]
I've added `resolve` back to the dependencies. My `require.resolve` solution didn't work, because it doesn't take the cwd into account

File: test/unit/stryker-cli.spec.ts (hunk 4 above)
Comment (korthout) [reply test/unit/stryker-cli.spec.ts]: Oops, you are right, I thought it said `stubs.resolve.throws(...)`

File: src/stryker-cli.ts [hunk 6]
```diff
@@ -25,40 +28,40 @@ export function run(log = console.log): Promise<void> {
...
-  RequireWrapper.require(strykerCli);
+  const stryker = localStryker();
+  NodeWrapper.require(stryker);
   return Promise.resolve();
 }
 
-function localStrykerCli() {
-  const dirname = path.dirname(RequireWrapper.resolve('stryker'));
+function localStryker() {
+  const stryker = resolve.sync('stryker', { basedir: NodeWrapper.cwd() });
```
Comment (korthout) [inline src/stryker-cli.ts]: Perhaps `resolve.sync` can be moved to NodeWrapper too.

File: src/stryker-cli.ts [hunk 7]
```diff
@@ -25,40 +28,40 @@ export function run(log = console.log): Promise<void> {
 }
 
 function runLocalStryker() {
-  const strykerCli = localStrykerCli();
-  RequireWrapper.require(strykerCli);
+  const stryker = localStryker();
```
Comment (korthout) [inline src/stryker-cli.ts]: Good naming ;)

File: src/stryker-cli.ts [hunk 8]
```diff
@@ -2,17 +2,20 @@ import * as path from 'path';
 import * as chalk from 'chalk';
 import * as inquirer from 'inquirer';
 import * as child from 'child_process';
-import RequireWrapper from './RequireWrapper';
+import NodeWrapper from './NodeWrapper';
+import * as resolve from 'resolve';
 
-export function run(log = console.log): Promise<void> {
+const installCommand = 'npm install --save-dev stryker stryker-api';
```
Comment (korthout) [inline src/stryker-cli.ts]: I'm not sure what the standard in TS is, but in Java it is common practice to name constants in uppercase. e.g. `INSTALL_COMMAND`. Perhaps this could make the intent of this value more clear.

File: src/stryker-cli.ts (hunk 6 above)
Comment (nicojs) [reply src/stryker-cli.ts]: Well.. it's not strictly necessary. The other once needed to be moved, because they cannot be (easily) mocked away for testing. Also, if we were to move it, we would need to find a different name, because we would not be *only* wrapping Node ;)

File: src/stryker-cli.ts (hunk 7 above)
Comment (nicojs) [reply src/stryker-cli.ts]: Yeah, `strykerCli` sounded strange to me. It is the cli... of stryker. But as this project is also called 'stryker-cli'...

File: src/stryker-cli.ts (hunk 8 above)
Comment (nicojs) [reply src/stryker-cli.ts]: Yeah, i've seen that for some typescript/javascript projects as well. It's not a general rule. The Angular team for example uses it (if i'm not mistaken), but the TypeScript team does not. We don't use it either. If you want, we can do it, i'm not strongly against it or anything.

Nothing about it in this styleguide:

https://github.com/basarat/typescript-book/blob/master/docs/styleguide/styleguide.md

**Comment by nicojs** [comment]
Thanks for the new review :star: ! I've commented on all your comments.

File: src/stryker-cli.ts (hunk 8 above)
Comment (korthout) [reply src/stryker-cli.ts]: If you don't already use it in the main project, then I wouldn't start using it here. Consistency is often the best option. Let's keep it how it is.

File: src/stryker-cli.ts (hunk 6 above)
Comment (korthout) [reply src/stryker-cli.ts]: Sounds reasonable. Let's keep it how it is.

**Comment by korthout** [comment]
Perfect. Seems like everything is good to go. I'll squash merge it in.
